modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/quek04/IBC/issues"
license="MIT"
[[mods]]
modId="ibc"
version="${file.jarVersion}"
displayName="Inconspicuous Bean Can"
credits=""
authors="quek"
description='''Just an ordinary can of beans...'''
[[dependencies.ibc]]
modId="forge"
mandatory=true
versionRange="[37,)"
ordering="NONE"
side="BOTH"
[[dependencies.ibc]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1]"
ordering="NONE"
side="BOTH"